---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
spec:
  capacity:
    storage: 5Gi    # Size of the storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete # Delete the PV if the attached PVC deleted - Data lost
  # persistentVolumeReclaimPolicy: Retain # PV wont get deleted even if PVC deleted, the data inside the PV will be saved
  hostPath:
    path: /data/app  # File path on local host/node of the pod. Can use cloud storages and attach here.
    
# ReadWriteOnce - One node can read / write once
# ReadOnlyMany - Read only many nodes read only at a time
# ReadWriteMany - Many nodes can read / write at a time

