apiVersion: v1
kind: pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: postgres
      image: postgres:15-alpine
      env:
        - name: POSTGRES_USER            # For postgres username and password is necessory to communicate with pod
          value: postgres 
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432            # Default listening port for postgres: 5432
          name: postgres