apiVersion: v1
kind: Service
metadata: 
  name: db
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - name: "db-service"
      port: 5432             # Port that can reach by the cluster
      targetPort: 5432       # Port exposing the service
  selector:
    app: db                 # tag from the db_pod.yml