apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - port: 8081               # Port that can reach by the cluster
      targetPort: 80           # Port exposing the service
      nodePort: 31001          # Port than can accessed by the outside internet
  selector:
    app: result