apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort       # Voting app will expose the port to the outside of cluster so choosing NodePost as Service
  ports:
    - port: 8080         # Port that can reach by the cluster
      targetPort: 80     # Port exposing the service
      nodePort: 31000    # Port than can accessed by the outside internet
  selector:
    app: vote