---
apiVersion: v1
kind: Service
metadata:
  name: external-db
spec:
  type: ExternalName
  externalName: <url of the website to access>
  ports:
    - port: 80/443
    
 # Used when the pods in out cluster have to access the public internet