---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007        # The port accessing by the public internet - port range from 30000 - 32767
      
 # Not too safe, used in test environments
 # Cluster can be accessed from public internet
 # Simpke external exposure